### ISSUE TITLE
Do not populate `text` attr in QR

### ISSUE THREAD

**Issue by ruscoder** [beda-software/fhir-sdc#90]
For consistency with sdc-qrf

```
resourceType: QuestionnaireResponse
item:
  - linkId: q-1
    text: Question text 
    answer:
      - valueString: 'answer'
```
